### ISSUE TITLE
A remark and a request

### ISSUE THREAD

**Issue by wboeke** [CCurl/c4#11]
This one does not work in c4:
  7 create seven ,
The program will try to find 'seven', but of course it cannot find it. In your c3 there is no problem.
And here is my request: the words 'do' and 'loop' are implemented, but often you also need '?do'. I tried to make it myself, but I'm not clever enough.

**Comment by CCurl** [comment]
Sorry ... c4 is fairly functional, but it is not my best work. It hard-codes alot of the immediate words, and is not very easy to modify.

I would strongly recommend using c3 instead. c3 is, IMO, better in pretty much every way. The current version has the base system (that used to be in the core.c3 file). It is also a more minimal implementation, also supports 64-bit floats, and we should be able to define ?DO without having to re-compile the base system.
